common:
  config:
    env: {}
    existingConfigMaps: []

  secrets:
    env: {}
    existingSecrets: []
    envFromKeys: {}
    files: {}
    existingSecretFiles: []

migration:
  enabled: true
  command:
    - /bin/sh
    - -ec
  args:
    - |
      ./app migrate up
      ./app rabbitmq topology apply
  resources: {}

api:
  enabled: true
  replicaCount: 1
  image:
    repository: petretiandrea/sms-gateway-service-v2
    tag: "3.1.0"
    pullPolicy: IfNotPresent
  env: {}
  secrets: {}
  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 8080
  containerPort: 8080
  resources: {}
  livenessProbe:
    enabled: true
    path: /health/live
    initialDelaySeconds: 20
    periodSeconds: 10
  readinessProbe:
    enabled: true
    path: /health/ready
    initialDelaySeconds: 10
    periodSeconds: 10

outbox:
  enabled: true
  replicaCount: 1
  image:
    repository: petretiandrea/outbox-forwarder
    tag: "v1.4.0"
    pullPolicy: IfNotPresent
  env: {}
  secrets: {}
  resources: {}
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
