{{- if .Values.outbox.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sms-gateway.outboxConfigName" . }}
  labels:
    {{- include "sms-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: "outbox"
data:
  outbox.yaml: |-
    source:
      type: postgres
      data:
        dsn: ${POSTGRES_DSN}
        table_name: outbox_messages
        batch_size: 100
        poll_interval: 1s
        initialize_schema: true

    channels:
      - name: internal.sms.send-requests
        publisher:
          type: rabbitmq
          data:
            url: ${RABBITMQ_DSN}
            exchange: sms
            routing_key: internal.sms
            content_type: application/json
      - name: internal.sms.attempt-requests
        publisher:
          type: rabbitmq
          data:
            url: ${RABBITMQ_DSN}
            exchange: sms
            routing_key: internal.sms
            content_type: application/json
{{- end }}
