{{- if .Values.common.secrets.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-gateway.secretFilesName" . }}
  labels:
    {{- include "sms-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $filename, $content := .Values.common.secrets.files }}
  {{ $filename }}: |-
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
