{{- if .Values.common.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-gateway.commonSecretName" . }}
  labels:
    {{- include "sms-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.common.secrets.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.api.enabled .Values.api.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-gateway.componentSecretName" (dict "root" . "component" "api") }}
  labels:
    {{- include "sms-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api"
type: Opaque
stringData:
  {{- range $key, $value := .Values.api.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.outbox.enabled .Values.outbox.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-gateway.componentSecretName" (dict "root" . "component" "outbox") }}
  labels:
    {{- include "sms-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: "outbox"
type: Opaque
stringData:
  {{- range $key, $value := .Values.outbox.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
