// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for EventNotificationType.
const (
	MessageDeliverFailed    EventNotificationType = "message.deliver.failed"
	MessageDeliverSucceeded EventNotificationType = "message.deliver.succeeded"
)

// AccountEntityDto defines model for AccountEntityDto.
type AccountEntityDto struct {
	AccountId   string     `json:"accountId"`
	ApiKey      string     `json:"apiKey"`
	CreateAt    *time.Time `json:"createAt,omitempty"`
	IsActive    bool       `json:"isActive"`
	PhoneNumber string     `json:"phoneNumber"`
}

// AdditionalMetadata defines model for AdditionalMetadata.
type AdditionalMetadata map[string]string

// CreateAccountRequestDto defines model for CreateAccountRequestDto.
type CreateAccountRequestDto struct {
	PhoneNumber string `json:"phoneNumber"`
}

// CreateWebhookRequest defines model for CreateWebhookRequest.
type CreateWebhookRequest struct {
	DefaultWebhookUrl *string `json:"defaultWebhookUrl,omitempty"`
	Enabled           bool    `json:"enabled"`
}

// EventNotificationDto defines model for EventNotificationDto.
type EventNotificationDto struct {
	Data      SmsEntityResponse     `json:"data"`
	EventType EventNotificationType `json:"eventType"`
	Metadata  AdditionalMetadata    `json:"metadata"`
}

// EventNotificationType defines model for EventNotificationType.
type EventNotificationType string

// FailedAttempt defines model for FailedAttempt.
type FailedAttempt struct {
	// Reason Reason of failure attempt
	Reason *string `json:"reason,omitempty"`
	Type   string  `json:"type"`
}

// PhoneEntityResponse defines model for PhoneEntityResponse.
type PhoneEntityResponse struct {
	Account   openapi_types.UUID `json:"account"`
	CreatedAt time.Time          `json:"createdAt"`
	FcmToken  *string            `json:"fcmToken,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Phone     string             `json:"phone"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// RegisterPhoneRequestDto defines model for RegisterPhoneRequestDto.
type RegisterPhoneRequestDto struct {
	Phone string `json:"phone"`
}

// SendAttempt defines model for SendAttempt.
type SendAttempt struct {
	// Attempt Number of attempt
	Attempt   int                `json:"attempt"`
	MessageId openapi_types.UUID `json:"messageId"`
	PhoneId   openapi_types.UUID `json:"phoneId"`
	Result    SendAttempt_Result `json:"result"`
}

// SendAttempt_Result defines model for SendAttempt.Result.
type SendAttempt_Result struct {
	union json.RawMessage
}

// SendSmsRequest defines model for SendSmsRequest.
type SendSmsRequest struct {
	Content  string                 `json:"content"`
	From     string                 `json:"from"`
	Metadata *AdditionalMetadata    `json:"metadata,omitempty"`
	To       string                 `json:"to"`
	Webhook  *WebhookOnDemandConfig `json:"webhook,omitempty"`
}

// SmsEntityResponse defines model for SmsEntityResponse.
type SmsEntityResponse struct {
	Content     string                         `json:"content"`
	CreatedAt   time.Time                      `json:"createdAt"`
	From        string                         `json:"from"`
	Id          openapi_types.UUID             `json:"id"`
	IsSent      bool                           `json:"isSent"`
	LastAttempt *SmsEntityResponse_LastAttempt `json:"lastAttempt,omitempty"`
	Owner       openapi_types.UUID             `json:"owner"`
	To          string                         `json:"to"`
	UpdatedAt   time.Time                      `json:"updatedAt"`
}

// SmsEntityResponse_LastAttempt defines model for SmsEntityResponse.LastAttempt.
type SmsEntityResponse_LastAttempt struct {
	AttemptCount int `json:"attemptCount"`
	union        json.RawMessage
}

// SuccessfulAttempt defines model for SuccessfulAttempt.
type SuccessfulAttempt struct {
	Type string `json:"type"`
}

// UpdatePhoneFirebaseTokenDto defines model for UpdatePhoneFirebaseTokenDto.
type UpdatePhoneFirebaseTokenDto struct {
	Token *string `json:"token,omitempty"`
}

// WebhookEntityResponse defines model for WebhookEntityResponse.
type WebhookEntityResponse struct {
	Enabled    bool    `json:"enabled"`
	WebhookURL *string `json:"webhookURL,omitempty"`
}

// WebhookOnDemandConfig defines model for WebhookOnDemandConfig.
type WebhookOnDemandConfig struct {
	Url *string `json:"url,omitempty"`
}

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	From   *string `form:"from,omitempty" json:"from,omitempty"`
	IsSent *bool   `form:"isSent,omitempty" json:"isSent,omitempty"`
}

// SendSmsParams defines parameters for SendSms.
type SendSmsParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = CreateAccountRequestDto

// ReportMessageStatusJSONRequestBody defines body for ReportMessageStatus for application/json ContentType.
type ReportMessageStatusJSONRequestBody = SendAttempt

// SendSmsJSONRequestBody defines body for SendSms for application/json ContentType.
type SendSmsJSONRequestBody = SendSmsRequest

// RegisterPhoneJSONRequestBody defines body for RegisterPhone for application/json ContentType.
type RegisterPhoneJSONRequestBody = RegisterPhoneRequestDto

// UpdateFcmTokenJSONRequestBody defines body for UpdateFcmToken for application/json ContentType.
type UpdateFcmTokenJSONRequestBody = UpdatePhoneFirebaseTokenDto

// PostWebhooksJSONRequestBody defines body for PostWebhooks for application/json ContentType.
type PostWebhooksJSONRequestBody = CreateWebhookRequest

// AsSuccessfulAttempt returns the union data inside the SendAttempt_Result as a SuccessfulAttempt
func (t SendAttempt_Result) AsSuccessfulAttempt() (SuccessfulAttempt, error) {
	var body SuccessfulAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSuccessfulAttempt overwrites any union data inside the SendAttempt_Result as the provided SuccessfulAttempt
func (t *SendAttempt_Result) FromSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSuccessfulAttempt performs a merge with any union data inside the SendAttempt_Result, using the provided SuccessfulAttempt
func (t *SendAttempt_Result) MergeSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFailedAttempt returns the union data inside the SendAttempt_Result as a FailedAttempt
func (t SendAttempt_Result) AsFailedAttempt() (FailedAttempt, error) {
	var body FailedAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedAttempt overwrites any union data inside the SendAttempt_Result as the provided FailedAttempt
func (t *SendAttempt_Result) FromFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedAttempt performs a merge with any union data inside the SendAttempt_Result, using the provided FailedAttempt
func (t *SendAttempt_Result) MergeFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SendAttempt_Result) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SendAttempt_Result) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "failure":
		return t.AsFailedAttempt()
	case "success":
		return t.AsSuccessfulAttempt()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SendAttempt_Result) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SendAttempt_Result) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSuccessfulAttempt returns the union data inside the SmsEntityResponse_LastAttempt as a SuccessfulAttempt
func (t SmsEntityResponse_LastAttempt) AsSuccessfulAttempt() (SuccessfulAttempt, error) {
	var body SuccessfulAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSuccessfulAttempt overwrites any union data inside the SmsEntityResponse_LastAttempt as the provided SuccessfulAttempt
func (t *SmsEntityResponse_LastAttempt) FromSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSuccessfulAttempt performs a merge with any union data inside the SmsEntityResponse_LastAttempt, using the provided SuccessfulAttempt
func (t *SmsEntityResponse_LastAttempt) MergeSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFailedAttempt returns the union data inside the SmsEntityResponse_LastAttempt as a FailedAttempt
func (t SmsEntityResponse_LastAttempt) AsFailedAttempt() (FailedAttempt, error) {
	var body FailedAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedAttempt overwrites any union data inside the SmsEntityResponse_LastAttempt as the provided FailedAttempt
func (t *SmsEntityResponse_LastAttempt) FromFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedAttempt performs a merge with any union data inside the SmsEntityResponse_LastAttempt, using the provided FailedAttempt
func (t *SmsEntityResponse_LastAttempt) MergeFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SmsEntityResponse_LastAttempt) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SmsEntityResponse_LastAttempt) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "failure":
		return t.AsFailedAttempt()
	case "success":
		return t.AsSuccessfulAttempt()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SmsEntityResponse_LastAttempt) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["attemptCount"], err = json.Marshal(t.AttemptCount)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'attemptCount': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *SmsEntityResponse_LastAttempt) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attemptCount"]; found {
		err = json.Unmarshal(raw, &t.AttemptCount)
		if err != nil {
			return fmt.Errorf("error reading 'attemptCount': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register new account
	// (POST /accounts)
	RegisterAccount(c *gin.Context)

	// (GET /accounts/{accountId})
	GetAccountById(c *gin.Context, accountId openapi_types.UUID)

	// (POST /attempts)
	ReportMessageStatus(c *gin.Context)
	// Get all filtered sms
	// (GET /messages)
	GetMessages(c *gin.Context, params GetMessagesParams)
	// Send a new sms
	// (POST /messages)
	SendSms(c *gin.Context, params SendSmsParams)
	// Get an sms
	// (GET /messages/{smsId})
	GetSmsById(c *gin.Context, smsId openapi_types.UUID)
	// Register new phone
	// (POST /phones)
	RegisterPhone(c *gin.Context)

	// (GET /phones/{phoneId})
	GetPhoneById(c *gin.Context, phoneId string)

	// (PUT /phones/{phoneId})
	UpdateFcmToken(c *gin.Context, phoneId openapi_types.UUID)
	// Enable webhook delivery
	// (POST /webhooks)
	PostWebhooks(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RegisterAccount operation middleware
func (siw *ServerInterfaceWrapper) RegisterAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterAccount(c)
}

// GetAccountById operation middleware
func (siw *ServerInterfaceWrapper) GetAccountById(c *gin.Context) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", c.Param("accountId"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accountId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountById(c, accountId)
}

// ReportMessageStatus operation middleware
func (siw *ServerInterfaceWrapper) ReportMessageStatus(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReportMessageStatus(c)
}

// GetMessages operation middleware
func (siw *ServerInterfaceWrapper) GetMessages(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessagesParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", c.Request.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "isSent" -------------

	err = runtime.BindQueryParameter("form", true, false, "isSent", c.Request.URL.Query(), &params.IsSent)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter isSent: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMessages(c, params)
}

// SendSms operation middleware
func (siw *ServerInterfaceWrapper) SendSms(c *gin.Context) {

	var err error

	c.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params SendSmsParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendSms(c, params)
}

// GetSmsById operation middleware
func (siw *ServerInterfaceWrapper) GetSmsById(c *gin.Context) {

	var err error

	// ------------- Path parameter "smsId" -------------
	var smsId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "smsId", c.Param("smsId"), &smsId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter smsId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSmsById(c, smsId)
}

// RegisterPhone operation middleware
func (siw *ServerInterfaceWrapper) RegisterPhone(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterPhone(c)
}

// GetPhoneById operation middleware
func (siw *ServerInterfaceWrapper) GetPhoneById(c *gin.Context) {

	var err error

	// ------------- Path parameter "phoneId" -------------
	var phoneId string

	err = runtime.BindStyledParameterWithOptions("simple", "phoneId", c.Param("phoneId"), &phoneId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter phoneId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPhoneById(c, phoneId)
}

// UpdateFcmToken operation middleware
func (siw *ServerInterfaceWrapper) UpdateFcmToken(c *gin.Context) {

	var err error

	// ------------- Path parameter "phoneId" -------------
	var phoneId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "phoneId", c.Param("phoneId"), &phoneId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter phoneId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateFcmToken(c, phoneId)
}

// PostWebhooks operation middleware
func (siw *ServerInterfaceWrapper) PostWebhooks(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostWebhooks(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/accounts", wrapper.RegisterAccount)
	router.GET(options.BaseURL+"/accounts/:accountId", wrapper.GetAccountById)
	router.POST(options.BaseURL+"/attempts", wrapper.ReportMessageStatus)
	router.GET(options.BaseURL+"/messages", wrapper.GetMessages)
	router.POST(options.BaseURL+"/messages", wrapper.SendSms)
	router.GET(options.BaseURL+"/messages/:smsId", wrapper.GetSmsById)
	router.POST(options.BaseURL+"/phones", wrapper.RegisterPhone)
	router.GET(options.BaseURL+"/phones/:phoneId", wrapper.GetPhoneById)
	router.PUT(options.BaseURL+"/phones/:phoneId", wrapper.UpdateFcmToken)
	router.POST(options.BaseURL+"/webhooks", wrapper.PostWebhooks)
}

type RegisterAccountRequestObject struct {
	Body *RegisterAccountJSONRequestBody
}

type RegisterAccountResponseObject interface {
	VisitRegisterAccountResponse(w http.ResponseWriter) error
}

type RegisterAccount201JSONResponse AccountEntityDto

func (response RegisterAccount201JSONResponse) VisitRegisterAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAccount400Response struct {
}

func (response RegisterAccount400Response) VisitRegisterAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetAccountByIdRequestObject struct {
	AccountId openapi_types.UUID `json:"accountId"`
}

type GetAccountByIdResponseObject interface {
	VisitGetAccountByIdResponse(w http.ResponseWriter) error
}

type GetAccountById200JSONResponse AccountEntityDto

func (response GetAccountById200JSONResponse) VisitGetAccountByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountById400Response struct {
}

func (response GetAccountById400Response) VisitGetAccountByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetAccountById404Response struct {
}

func (response GetAccountById404Response) VisitGetAccountByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ReportMessageStatusRequestObject struct {
	Body *ReportMessageStatusJSONRequestBody
}

type ReportMessageStatusResponseObject interface {
	VisitReportMessageStatusResponse(w http.ResponseWriter) error
}

type ReportMessageStatus202Response struct {
}

func (response ReportMessageStatus202Response) VisitReportMessageStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type ReportMessageStatus400Response struct {
}

func (response ReportMessageStatus400Response) VisitReportMessageStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ReportMessageStatus500Response struct {
}

func (response ReportMessageStatus500Response) VisitReportMessageStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetMessagesRequestObject struct {
	Params GetMessagesParams
}

type GetMessagesResponseObject interface {
	VisitGetMessagesResponse(w http.ResponseWriter) error
}

type GetMessages200JSONResponse struct {
	Messages *[]SmsEntityResponse `json:"messages,omitempty"`
}

func (response GetMessages200JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMessages400Response struct {
}

func (response GetMessages400Response) VisitGetMessagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type SendSmsRequestObject struct {
	Params SendSmsParams
	Body   *SendSmsJSONRequestBody
}

type SendSmsResponseObject interface {
	VisitSendSmsResponse(w http.ResponseWriter) error
}

type SendSms201JSONResponse SmsEntityResponse

func (response SendSms201JSONResponse) VisitSendSmsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SendSms400Response struct {
}

func (response SendSms400Response) VisitSendSmsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetSmsByIdRequestObject struct {
	SmsId openapi_types.UUID `json:"smsId"`
}

type GetSmsByIdResponseObject interface {
	VisitGetSmsByIdResponse(w http.ResponseWriter) error
}

type GetSmsById200JSONResponse SmsEntityResponse

func (response GetSmsById200JSONResponse) VisitGetSmsByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSmsById404Response struct {
}

func (response GetSmsById404Response) VisitGetSmsByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type RegisterPhoneRequestObject struct {
	Body *RegisterPhoneJSONRequestBody
}

type RegisterPhoneResponseObject interface {
	VisitRegisterPhoneResponse(w http.ResponseWriter) error
}

type RegisterPhone201JSONResponse string

func (response RegisterPhone201JSONResponse) VisitRegisterPhoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterPhone400Response struct {
}

func (response RegisterPhone400Response) VisitRegisterPhoneResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetPhoneByIdRequestObject struct {
	PhoneId string `json:"phoneId"`
}

type GetPhoneByIdResponseObject interface {
	VisitGetPhoneByIdResponse(w http.ResponseWriter) error
}

type GetPhoneById200JSONResponse PhoneEntityResponse

func (response GetPhoneById200JSONResponse) VisitGetPhoneByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPhoneById400Response struct {
}

func (response GetPhoneById400Response) VisitGetPhoneByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetPhoneById404Response struct {
}

func (response GetPhoneById404Response) VisitGetPhoneByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateFcmTokenRequestObject struct {
	PhoneId openapi_types.UUID `json:"phoneId"`
	Body    *UpdateFcmTokenJSONRequestBody
}

type UpdateFcmTokenResponseObject interface {
	VisitUpdateFcmTokenResponse(w http.ResponseWriter) error
}

type UpdateFcmToken200JSONResponse string

func (response UpdateFcmToken200JSONResponse) VisitUpdateFcmTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFcmToken400Response struct {
}

func (response UpdateFcmToken400Response) VisitUpdateFcmTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostWebhooksRequestObject struct {
	Body *PostWebhooksJSONRequestBody
}

type PostWebhooksResponseObject interface {
	VisitPostWebhooksResponse(w http.ResponseWriter) error
}

type PostWebhooks200JSONResponse WebhookEntityResponse

func (response PostWebhooks200JSONResponse) VisitPostWebhooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostWebhooks400Response struct {
}

func (response PostWebhooks400Response) VisitPostWebhooksResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register new account
	// (POST /accounts)
	RegisterAccount(ctx context.Context, request RegisterAccountRequestObject) (RegisterAccountResponseObject, error)

	// (GET /accounts/{accountId})
	GetAccountById(ctx context.Context, request GetAccountByIdRequestObject) (GetAccountByIdResponseObject, error)

	// (POST /attempts)
	ReportMessageStatus(ctx context.Context, request ReportMessageStatusRequestObject) (ReportMessageStatusResponseObject, error)
	// Get all filtered sms
	// (GET /messages)
	GetMessages(ctx context.Context, request GetMessagesRequestObject) (GetMessagesResponseObject, error)
	// Send a new sms
	// (POST /messages)
	SendSms(ctx context.Context, request SendSmsRequestObject) (SendSmsResponseObject, error)
	// Get an sms
	// (GET /messages/{smsId})
	GetSmsById(ctx context.Context, request GetSmsByIdRequestObject) (GetSmsByIdResponseObject, error)
	// Register new phone
	// (POST /phones)
	RegisterPhone(ctx context.Context, request RegisterPhoneRequestObject) (RegisterPhoneResponseObject, error)

	// (GET /phones/{phoneId})
	GetPhoneById(ctx context.Context, request GetPhoneByIdRequestObject) (GetPhoneByIdResponseObject, error)

	// (PUT /phones/{phoneId})
	UpdateFcmToken(ctx context.Context, request UpdateFcmTokenRequestObject) (UpdateFcmTokenResponseObject, error)
	// Enable webhook delivery
	// (POST /webhooks)
	PostWebhooks(ctx context.Context, request PostWebhooksRequestObject) (PostWebhooksResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// RegisterAccount operation middleware
func (sh *strictHandler) RegisterAccount(ctx *gin.Context) {
	var request RegisterAccountRequestObject

	var body RegisterAccountJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterAccount(ctx, request.(RegisterAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterAccountResponseObject); ok {
		if err := validResponse.VisitRegisterAccountResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccountById operation middleware
func (sh *strictHandler) GetAccountById(ctx *gin.Context, accountId openapi_types.UUID) {
	var request GetAccountByIdRequestObject

	request.AccountId = accountId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccountById(ctx, request.(GetAccountByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccountById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAccountByIdResponseObject); ok {
		if err := validResponse.VisitGetAccountByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReportMessageStatus operation middleware
func (sh *strictHandler) ReportMessageStatus(ctx *gin.Context) {
	var request ReportMessageStatusRequestObject

	var body ReportMessageStatusJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReportMessageStatus(ctx, request.(ReportMessageStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportMessageStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ReportMessageStatusResponseObject); ok {
		if err := validResponse.VisitReportMessageStatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMessages operation middleware
func (sh *strictHandler) GetMessages(ctx *gin.Context, params GetMessagesParams) {
	var request GetMessagesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMessages(ctx, request.(GetMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMessages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetMessagesResponseObject); ok {
		if err := validResponse.VisitGetMessagesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendSms operation middleware
func (sh *strictHandler) SendSms(ctx *gin.Context, params SendSmsParams) {
	var request SendSmsRequestObject

	request.Params = params

	var body SendSmsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendSms(ctx, request.(SendSmsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendSms")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SendSmsResponseObject); ok {
		if err := validResponse.VisitSendSmsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSmsById operation middleware
func (sh *strictHandler) GetSmsById(ctx *gin.Context, smsId openapi_types.UUID) {
	var request GetSmsByIdRequestObject

	request.SmsId = smsId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSmsById(ctx, request.(GetSmsByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSmsById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSmsByIdResponseObject); ok {
		if err := validResponse.VisitGetSmsByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterPhone operation middleware
func (sh *strictHandler) RegisterPhone(ctx *gin.Context) {
	var request RegisterPhoneRequestObject

	var body RegisterPhoneJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterPhone(ctx, request.(RegisterPhoneRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterPhone")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterPhoneResponseObject); ok {
		if err := validResponse.VisitRegisterPhoneResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPhoneById operation middleware
func (sh *strictHandler) GetPhoneById(ctx *gin.Context, phoneId string) {
	var request GetPhoneByIdRequestObject

	request.PhoneId = phoneId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPhoneById(ctx, request.(GetPhoneByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPhoneById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPhoneByIdResponseObject); ok {
		if err := validResponse.VisitGetPhoneByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateFcmToken operation middleware
func (sh *strictHandler) UpdateFcmToken(ctx *gin.Context, phoneId openapi_types.UUID) {
	var request UpdateFcmTokenRequestObject

	request.PhoneId = phoneId

	var body UpdateFcmTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateFcmToken(ctx, request.(UpdateFcmTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateFcmToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateFcmTokenResponseObject); ok {
		if err := validResponse.VisitUpdateFcmTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostWebhooks operation middleware
func (sh *strictHandler) PostWebhooks(ctx *gin.Context) {
	var request PostWebhooksRequestObject

	var body PostWebhooksJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostWebhooks(ctx, request.(PostWebhooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostWebhooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostWebhooksResponseObject); ok {
		if err := validResponse.VisitPostWebhooksResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
