
app:
  name: 'sms-gateway'

postgres:
  dsn: 'postgres://sms_gateway:sms_gateway@localhost:5432/sms_gateway?sslmode=disable'

rabbitmq:
  dsn: 'amqp://sms_gateway:sms_gateway@localhost:5672/'

dry_run: 'true'

firebase:
  credentials_file: '../be-aesthetic-admin-sdk.json'
