{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: app-port-{{ . }}-svc
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
  selector:
    {{- tpl (toYaml .Values.labels) . | nindent 4 }}
{{- end }}
