apiVersion: v2
name: sms-gateway
description: SMS gateway deployment based on bjw-s app-template
type: application
version: 0.1.0
appVersion: "3.0.4"
kubeVersion: ">=1.28.0-0"
dependencies:
  - name: app-template
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts
