namespace: "default"
name: "sms-gateway-service"
labels:
  app: "sms-gateway-api"

replicaCount: 1

image:
  repository: petretiandrea/sms-gateway-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  create: true
  type: ClusterIP
  ports:
    - 8080

envConfig:
  FIREBASECONFIG_CREDENTIALSFILE: /app/be-aesthetic-admin-sdk.json
  FIREBASECONFIG_SMS: sms-dev
  FIREBASECONFIG_USERACCOUNT: user-account-dev
  FIREBASECONFIG_PHONE: phone-dev
  DRYRUN: true

secretFiles:
  - name: "firebase-admin-config"
    mountPath: "/app/be-aesthetic-admin-sdk.json"
    subPath: "firebase-admin.json"

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  failureThreshold: 10
  periodSeconds: 30

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  failureThreshold: 10
  periodSeconds: 30

# TODO: add ingress zone

