app-template:
  controllers:
    outbox-forwarder:
      forceRename: sms-gateway-outbox-forwarder
      type: deployment
      replicas: 1
      strategy: RollingUpdate
      rollingUpdate:
        surge: 1
        unavailable: "0"
      containers:
        main:
          image:
            repository: petretiandrea/outbox-forwarder
            tag: "v1.1.0"
            pullPolicy: IfNotPresent
          env:
            OUTBOX_SOURCE__DATA__DSN:
              valueFrom:
                secretKeyRef:
                  name: sms-gateway-outbox-forwarder-secrets
                  key: postgres-dsn
            OUTBOX_CHANNELS__0__PUBLISHER__DATA__URL:
              valueFrom:
                secretKeyRef:
                  name: sms-gateway-outbox-forwarder-secrets
                  key: rabbitmq-url

  configMaps:
    outbox-forwarder-config:
      forceRename: sms-gateway-outbox-forwarder-config
      labels:
        app: sms-gateway-outbox-forwarder
      data:
        outbox.yaml: |
          source:
            type: postgres
            data:
              table_name: outbox_messages
              batch_size: 100
              poll_interval: 1s
              initialize_schema: true

          channels:
            - name: beaesthetic.sms.send.internal
              publisher:
                type: rabbitmq
                data:
                  exchange: beaesthetic.sms
                  routing_key: sms.send.internal.requested
                  content_type: application/json

  persistence:
    outbox-forwarder-config:
      type: configMap
      identifier: outbox-forwarder-config
      advancedMounts:
        outbox-forwarder:
          main:
            - path: /etc/outbox/outbox.yaml
              subPath: outbox.yaml
              readOnly: true

