apiVersion: v1
kind: Secret
metadata:
  name: sms-gateway-connection-secrets
type: Opaque
stringData:
  POSTGRES_DSN: "postgres://user:password@postgres.example.com:5432/sms_gateway?sslmode=require"
  RABBITMQ_DSN: "amqps://user:password@rabbitmq.example.com:5671/sms-gateway"
