name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'api-spec/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      
      - name: Docs workdir
        run: cd docs

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: |
            npm run gen-api-docs    
            npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            folder: ./docs/build
