name: Release sms gateway microservice

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

env:
  TARGET_PLATFORMS: linux/amd64, linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Docker image"
    outputs:
      tag_deploy: ${{ steps.tag_deploy.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta for SMS Gateway Service
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: petretiandrea/sms-gateway-service
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Build and push SMS Gateway Service
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}

      - name: Get image tag for deploy
        id: tag_deploy
        run: echo "tag=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_OUTPUT;

#  deploy:
#    needs: [build]
#    name: "Deploy to K8s"
#    uses: ./.github/workflows/k8s-deploy-helm.yml
#    with:
#      microservice-name: sms-gateway-service
#      helm-path: "./helm/"
#      image-tag: "${{ needs.build.outputs.tag_deploy }}"